from enum import StrEnum


class HookType(StrEnum):
    ON_CHAT_START = "ON_CHAT_START"
    ON_CHAT_ERROR = "ON_CHAT_ERROR"
    ON_CHAT_COMPLETE = "ON_CHAT_COMPLETE"

    ON_INLINE_REVIEW_START = "ON_INLINE_REVIEW_START"
    ON_INLINE_REVIEW_COMPLETE = "ON_INLINE_REVIEW_COMPLETE"

    ON_CONTEXT_REVIEW_START = "ON_CONTEXT_REVIEW_START"
    ON_CONTEXT_REVIEW_COMPLETE = "ON_CONTEXT_REVIEW_COMPLETE"

    ON_SUMMARY_REVIEW_START = "ON_SUMMARY_REVIEW_START"
    ON_SUMMARY_REVIEW_COMPLETE = "ON_SUMMARY_REVIEW_COMPLETE"

    ON_INLINE_REPLY_REVIEW_START = "ON_INLINE_REPLY_REVIEW_START"
    ON_INLINE_REPLY_REVIEW_COMPLETE = "ON_INLINE_REPLY_REVIEW_COMPLETE"

    ON_SUMMARY_REPLY_REVIEW_START = "ON_SUMMARY_REPLY_REVIEW_START"
    ON_SUMMARY_REPLY_REVIEW_COMPLETE = "ON_SUMMARY_REPLY_REVIEW_COMPLETE"

    ON_INLINE_COMMENT_START = "ON_INLINE_COMMENT_START"
    ON_INLINE_COMMENT_ERROR = "ON_INLINE_COMMENT_ERROR"
    ON_INLINE_COMMENT_COMPLETE = "ON_INLINE_COMMENT_COMPLETE"

    ON_SUMMARY_COMMENT_START = "ON_SUMMARY_COMMENT_START"
    ON_SUMMARY_COMMENT_ERROR = "ON_SUMMARY_COMMENT_ERROR"
    ON_SUMMARY_COMMENT_COMPLETE = "ON_SUMMARY_COMMENT_COMPLETE"

    ON_INLINE_COMMENT_REPLY_START = "ON_INLINE_COMMENT_REPLY_START"
    ON_INLINE_COMMENT_REPLY_ERROR = "ON_INLINE_COMMENT_REPLY_ERROR"
    ON_INLINE_COMMENT_REPLY_COMPLETE = "ON_INLINE_COMMENT_REPLY_COMPLETE"

    ON_SUMMARY_COMMENT_REPLY_START = "ON_SUMMARY_COMMENT_REPLY_START"
    ON_SUMMARY_COMMENT_REPLY_ERROR = "ON_SUMMARY_COMMENT_REPLY_ERROR"
    ON_SUMMARY_COMMENT_REPLY_COMPLETE = "ON_SUMMARY_COMMENT_REPLY_COMPLETE"

    ON_CLEAR_INLINE_COMMENTS_START = "ON_CLEAR_INLINE_COMMENTS_START"
    ON_CLEAR_INLINE_COMMENTS_ERROR = "ON_CLEAR_INLINE_COMMENTS_ERROR"
    ON_CLEAR_INLINE_COMMENTS_COMPLETE = "ON_CLEAR_INLINE_COMMENTS_COMPLETE"

    ON_CLEAR_SUMMARY_COMMENTS_START = "ON_CLEAR_SUMMARY_COMMENTS_START"
    ON_CLEAR_SUMMARY_COMMENTS_ERROR = "ON_CLEAR_SUMMARY_COMMENTS_ERROR"
    ON_CLEAR_SUMMARY_COMMENTS_COMPLETE = "ON_CLEAR_SUMMARY_COMMENTS_COMPLETE"
