name: Test

on:
  workflow_call:
    inputs:
      config-file:
        type: string
        default: "./argus_review/tests/configs/config-test.yaml"
        required: false
      python-version:
        type: string
        default: "3.12"
        required: false

jobs:
  action:
    runs-on: self-hosted
    env:
      AI_REVIEW_CONFIG_FILE_YAML: ${{ inputs.config-file }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up virtualenv
        run: python3.12 -m venv .venv

      - name: Install dependencies
        run: .venv/bin/pip install .[test] pytest pytest-cov

      - name: Run tests
        run: .venv/bin/pytest --cov=argus_review --cov-report=xml --cov-report=term-missing

      - name: Upload coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
          fail_ci_if_error: true
