name: Lint

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.12"
        required: false

jobs:
  action:
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - run: pip install ruff
      - run: ruff check argus_review
    runs-on: ubuntu-latest
