name: Lint

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.12"
        required: false

jobs:
  action:
    runs-on: self-hosted
    container:
      image: python:${{ inputs.python-version }}-slim
    steps:
      - name: Install git
        run: apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

      - uses: actions/checkout@v6
      - run: pip install ruff
      - run: ruff check argus_review
