name: Web Deploy

on:
  workflow_call:

jobs:
  action:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v6

      - name: Install web dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: web
          command: pages deploy dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
